import type { Stock, Watchlist, Portfolio, NewsArticle, ChatMessage, InvestorProfile } from "@/types";

export const MOCK_STOCKS: Stock[] = [
  {
    id: 1,
    ticker: "RELIANCE",
    company: "Reliance Industries",
    sector: "Energy",
    exchange: "NSE",
    currentPrice: 2850.5,
    change: 45.25,
    changePercent: 1.61,
    volume: 2500000,
    marketCap: 1900000000000,
  },
  {
    id: 2,
    ticker: "TCS",
    company: "Tata Consultancy Services",
    sector: "IT",
    exchange: "NSE",
    currentPrice: 3450.75,
    change: 68.5,
    changePercent: 2.03,
    volume: 1800000,
    marketCap: 1400000000000,
  },
  {
    id: 3,
    ticker: "INFY",
    company: "Infosys",
    sector: "IT",
    exchange: "NSE",
    currentPrice: 1850.25,
    change: -25.5,
    changePercent: -1.36,
    volume: 3200000,
    marketCap: 770000000000,
  },
  {
    id: 4,
    ticker: "HDFCBANK",
    company: "HDFC Bank",
    sector: "Finance",
    exchange: "NSE",
    currentPrice: 1650.5,
    change: 28.75,
    changePercent: 1.77,
    volume: 2100000,
    marketCap: 1100000000000,
  },
  {
    id: 5,
    ticker: "ICICIBANK",
    company: "ICICI Bank",
    sector: "Finance",
    exchange: "NSE",
    currentPrice: 950.25,
    change: 15.5,
    changePercent: 1.65,
    volume: 2800000,
    marketCap: 650000000000,
  },
  {
    id: 6,
    ticker: "SBIN",
    company: "State Bank of India",
    sector: "Finance",
    exchange: "NSE",
    currentPrice: 650.75,
    change: -12.5,
    changePercent: -1.88,
    volume: 3500000,
    marketCap: 580000000000,
  },
  {
    id: 7,
    ticker: "ITC",
    company: "ITC Limited",
    sector: "FMCG",
    exchange: "NSE",
    currentPrice: 410.5,
    change: 8.25,
    changePercent: 2.05,
    volume: 2200000,
    marketCap: 420000000000,
  },
];

export const MOCK_WATCHLISTS: Watchlist[] = [
  {
    id: "1",
    name: "Tech Giants",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    stocks: [MOCK_STOCKS[1], MOCK_STOCKS[2]],
    stockCount: 2,
  },
  {
    id: "2",
    name: "Banking Sector",
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    stocks: [MOCK_STOCKS[3], MOCK_STOCKS[4], MOCK_STOCKS[5]],
    stockCount: 3,
  },
  {
    id: "3",
    name: "Energy & Utilities",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    stocks: [MOCK_STOCKS[0]],
    stockCount: 1,
  },
];

export const MOCK_PORTFOLIO: Portfolio = {
  totalValue: 750000,
  totalInvested: 680000,
  totalGainLoss: 70000,
  totalGainLossPercent: 10.29,
  holdings: [
    {
      id: "h1",
      stock: MOCK_STOCKS[1],
      quantity: 50,
      averagePrice: 3200,
      currentPrice: 3450.75,
      value: 172537.5,
      gainLoss: 12537.5,
      gainLossPercent: 7.85,
    },
    {
      id: "h2",
      stock: MOCK_STOCKS[3],
      quantity: 100,
      averagePrice: 1550,
      currentPrice: 1650.5,
      value: 165050,
      gainLoss: 10050,
      gainLossPercent: 6.48,
    },
    {
      id: "h3",
      stock: MOCK_STOCKS[0],
      quantity: 30,
      averagePrice: 2750,
      currentPrice: 2850.5,
      value: 85515,
      gainLoss: 3015,
      gainLossPercent: 3.65,
    },
    {
      id: "h4",
      stock: MOCK_STOCKS[2],
      quantity: 200,
      averagePrice: 1900,
      currentPrice: 1850.25,
      value: 370050,
      gainLoss: -9950,
      gainLossPercent: -2.62,
    },
  ],
  sectorAllocation: [
    { sector: "IT", value: 315537.5, percent: 42.07, color: "#2563EB" },
    { sector: "Finance", value: 165050, percent: 22.01, color: "#10B981" },
    { sector: "Energy", value: 85515, percent: 11.40, color: "#F59E0B" },
    { sector: "Consumer", value: 184347.5, percent: 24.58, color: "#8B5CF6" },
  ],
};

export const MOCK_NEWS: NewsArticle[] = [
  {
    id: "n1",
    headline: "TCS Reports Strong Q3 Results, Beats Expectations",
    source: "Economic Times",
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    sentiment: "positive",
    companies: ["TCS"],
    link: "https://economictimes.indiatimes.com",
    summary: "Tata Consultancy Services announced Q3 results with revenue growth of 2.3% QoQ...",
  },
  {
    id: "n2",
    headline: "RBI Holds Rates Steady; Market Down 200 Points",
    source: "Moneycontrol",
    publishedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    sentiment: "neutral",
    companies: ["RELIANCE", "SBIN", "HDFCBANK"],
    link: "https://moneycontrol.com",
    summary: "The Reserve Bank of India maintained policy rates at 6.5%, citing inflation concerns...",
  },
  {
    id: "n3",
    headline: "ICICI Bank Launches New Digital Payment Service",
    source: "Bloomberg Quint",
    publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    sentiment: "positive",
    companies: ["ICICIBANK"],
    link: "https://bloombergquint.com",
    summary: "ICICI Bank announced a new digital payment service targeting retail customers...",
  },
  {
    id: "n4",
    headline: "Infosys Cuts Full-Year Guidance Amid Weak Demand",
    source: "Reuters",
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    sentiment: "negative",
    companies: ["INFY"],
    link: "https://reuters.com",
    summary: "Infosys reduced FY24 guidance citing weak client spending and ongoing uncertainty...",
  },
];

export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: "m1",
    content: "Should I buy Reliance now?",
    role: "user",
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: "m2",
    content:
      "Reliance Industries is trading at ₹2,850.50 with a positive momentum of +1.61% today. Based on recent market news and technical indicators, the stock shows strong fundamentals with a market cap of ₹19 trillion. Current P/E ratio suggests moderate valuation. However, consider your portfolio allocation and investment horizon before making a decision.",
    role: "assistant",
    timestamp: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    citations: [
      {
        id: "c1",
        title: "Reliance Q3 Earnings Report",
        source: "Screener.in",
        url: "https://screener.in/company/RELIANCE",
        publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        snippet: "Strong Q3 performance with revenue growth of 8.2%...",
      },
      {
        id: "c2",
        title: "Reliance Industries Annual Report 2023",
        source: "Annual Report",
        url: "https://reliance.com/annual-report",
        publishedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        snippet: "Detailed financial analysis and future outlook...",
      },
    ],
  },
];

export const MOCK_INVESTOR_PROFILE: InvestorProfile = {
  riskAppetite: "moderate",
  investmentHorizon: "long",
  preferredSectors: ["IT", "Finance", "Energy"],
  avoidedSectors: ["Metals"],
  dividendPreference: "moderate",
  growthPreference: "moderate",
};

export const SEARCH_RESULTS = [
  { id: 1, ticker: "RELIANCE", company: "Reliance Industries" },
  { id: 2, ticker: "TCS", company: "Tata Consultancy Services" },
  { id: 3, ticker: "INFY", company: "Infosys" },
  { id: 4, ticker: "HDFCBANK", company: "HDFC Bank" },
  { id: 5, ticker: "ICICIBANK", company: "ICICI Bank" },
  { id: 6, ticker: "SBIN", company: "State Bank of India" },
  { id: 7, ticker: "ITC", company: "ITC Limited" },
];
