"""add investor profile table

Revision ID: ab27ea2f8c6d
Revises: 721958a33577
Create Date: 2026-08-01 16:25:15.762014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab27ea2f8c6d'
down_revision: Union[str, Sequence[str], None] = '721958a33577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('risk_profile', sa.String(length=50), nullable=True),
    sa.Column('investment_horizon', sa.String(length=50), nullable=True),
    sa.Column('investment_style', sa.String(length=50), nullable=True),
    sa.Column('preferred_market', sa.String(length=100), nullable=True),
    sa.Column('preferred_sectors', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investor_profiles_id'), 'investor_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_investor_profiles_user_id'), 'investor_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investor_profiles_user_id'), table_name='investor_profiles')
    op.drop_index(op.f('ix_investor_profiles_id'), table_name='investor_profiles')
    op.drop_table('investor_profiles')
    # ### end Alembic commands ###
